name = "tcs-awei"
compatibility_date = "2024-09-01"
main = "src/index.js"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "foodie-awei-db"
database_id = "1f2a4a2b-2c90-438b-af99-96fe736634c5"
